package com.example.habittracker.presentation.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

private val organizeIconVector: ImageVector = habitIconVector("GridView") {
    moveTo(3.0f, 3.0f)
    verticalLineToRelative(8.0f)
    horizontalLineToRelative(8.0f)
    verticalLineTo(3.0f)
    horizontalLineTo(3.0f)
    close()
    moveTo(9.0f, 9.0f)
    horizontalLineTo(5.0f)
    verticalLineTo(5.0f)
    horizontalLineToRelative(4.0f)
    verticalLineTo(9.0f)
    close()
    moveTo(3.0f, 13.0f)
    verticalLineToRelative(8.0f)
    horizontalLineToRelative(8.0f)
    verticalLineToRelative(-8.0f)
    horizontalLineTo(3.0f)
    close()
    moveTo(9.0f, 19.0f)
    horizontalLineTo(5.0f)
    verticalLineToRelative(-4.0f)
    horizontalLineToRelative(4.0f)
    verticalLineTo(19.0f)
    close()
    moveTo(13.0f, 3.0f)
    verticalLineToRelative(8.0f)
    horizontalLineToRelative(8.0f)
    verticalLineTo(3.0f)
    horizontalLineTo(13.0f)
    close()
    moveTo(19.0f, 9.0f)
    horizontalLineToRelative(-4.0f)
    verticalLineTo(5.0f)
    horizontalLineToRelative(4.0f)
    verticalLineTo(9.0f)
    close()
    moveTo(13.0f, 13.0f)
    verticalLineToRelative(8.0f)
    horizontalLineToRelative(8.0f)
    verticalLineToRelative(-8.0f)
    horizontalLineTo(13.0f)
    close()
    moveTo(19.0f, 19.0f)
    horizontalLineToRelative(-4.0f)
    verticalLineToRelative(-4.0f)
    horizontalLineToRelative(4.0f)
    verticalLineTo(19.0f)
    close()
}

@Suppress("UnusedReceiverParameter")
internal val HabitTrackerIcons.organizeIcon: ImageVector
    get() = organizeIconVector
