package com.example.habittracker.presentation.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

private val studyIconVector: ImageVector = habitIconVector("CalendarMonth") {
    moveTo(19.0f, 4.0f)
    horizontalLineToRelative(-1.0f)
    verticalLineTo(2.0f)
    horizontalLineToRelative(-2.0f)
    verticalLineToRelative(2.0f)
    horizontalLineTo(8.0f)
    verticalLineTo(2.0f)
    horizontalLineTo(6.0f)
    verticalLineToRelative(2.0f)
    horizontalLineTo(5.0f)
    curveTo(3.89f, 4.0f, 3.01f, 4.9f, 3.01f, 6.0f)
    lineTo(3.0f, 20.0f)
    curveToRelative(0.0f, 1.1f, 0.89f, 2.0f, 2.0f, 2.0f)
    horizontalLineToRelative(14.0f)
    curveToRelative(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f)
    verticalLineTo(6.0f)
    curveTo(21.0f, 4.9f, 20.1f, 4.0f, 19.0f, 4.0f)
    close()
    moveTo(19.0f, 20.0f)
    horizontalLineTo(5.0f)
    verticalLineTo(10.0f)
    horizontalLineToRelative(14.0f)
    verticalLineTo(20.0f)
    close()
    moveTo(19.0f, 8.0f)
    horizontalLineTo(5.0f)
    verticalLineTo(6.0f)
    horizontalLineToRelative(14.0f)
    verticalLineTo(8.0f)
    close()
    moveTo(9.0f, 14.0f)
    horizontalLineTo(7.0f)
    verticalLineToRelative(-2.0f)
    horizontalLineToRelative(2.0f)
    verticalLineTo(14.0f)
    close()
    moveTo(13.0f, 14.0f)
    horizontalLineToRelative(-2.0f)
    verticalLineToRelative(-2.0f)
    horizontalLineToRelative(2.0f)
    verticalLineTo(14.0f)
    close()
    moveTo(17.0f, 14.0f)
    horizontalLineToRelative(-2.0f)
    verticalLineToRelative(-2.0f)
    horizontalLineToRelative(2.0f)
    verticalLineTo(14.0f)
    close()
    moveTo(9.0f, 18.0f)
    horizontalLineTo(7.0f)
    verticalLineToRelative(-2.0f)
    horizontalLineToRelative(2.0f)
    verticalLineTo(18.0f)
    close()
    moveTo(13.0f, 18.0f)
    horizontalLineToRelative(-2.0f)
    verticalLineToRelative(-2.0f)
    horizontalLineToRelative(2.0f)
    verticalLineTo(18.0f)
    close()
    moveTo(17.0f, 18.0f)
    horizontalLineToRelative(-2.0f)
    verticalLineToRelative(-2.0f)
    horizontalLineToRelative(2.0f)
    verticalLineTo(18.0f)
    close()
}

@Suppress("UnusedReceiverParameter")
internal val HabitTrackerIcons.studyIcon: ImageVector
    get() = studyIconVector
